"""Wiii Connect contract helpers."""

from .adapter_v1 import (
    WIII_CONNECT_ADAPTER_VERSION,
    WiiiConnectAuditEvent,
    WiiiConnectConnectionRecordV1,
    WiiiConnectExecutionDecision,
    WiiiConnectExecutionRequest,
    WiiiConnectProviderRegistryEntry,
    WiiiConnectRequiredField,
    WiiiConnectScopeGrant,
    WiiiConnectVaultSecretRef,
    decide_external_execution,
    is_connection_baseline_ready,
    normalize_connection_state,
)
from .callback_boundary import (
    WIII_CONNECT_CALLBACK_CONTRACT_VERSION,
    WiiiConnectCallbackAuditEvent,
    WiiiConnectCallbackDecision,
    WiiiConnectCallbackRequest,
    provider_callback_decision,
    provider_callback_decision_for_entry,
)
from .connection_sessions import (
    WIII_CONNECT_SESSION_CONTRACT_VERSION,
    WiiiConnectConnectionSessionAuditEvent,
    WiiiConnectProviderConnectionStatus,
    WiiiConnectSessionStartDecision,
    WiiiConnectSessionStartRequest,
    begin_connection_session,
    provider_connection_status,
    provider_connection_status_for_entry,
    scope_grant_from_mapping,
)
from .provider_registry import (
    WIII_CONNECT_PROVIDER_REGISTRY_VERSION,
    get_wiii_connect_provider_entry,
    list_wiii_connect_provider_registry,
    provider_registry_public_metadata,
)
from .snapshot import (
    WIII_CONNECT_SNAPSHOT_VERSION,
    WiiiConnectionRecord,
    WiiiConnectionScopes,
    WiiiConnectionSnapshot,
    WiiiPathCapabilityRecord,
    build_wiii_connect_snapshot,
)

__all__ = [
    "WIII_CONNECT_ADAPTER_VERSION",
    "WIII_CONNECT_CALLBACK_CONTRACT_VERSION",
    "WIII_CONNECT_SESSION_CONTRACT_VERSION",
    "WiiiConnectAuditEvent",
    "WiiiConnectCallbackAuditEvent",
    "WiiiConnectCallbackDecision",
    "WiiiConnectCallbackRequest",
    "WiiiConnectConnectionSessionAuditEvent",
    "WiiiConnectConnectionRecordV1",
    "WiiiConnectExecutionDecision",
    "WiiiConnectExecutionRequest",
    "WiiiConnectProviderConnectionStatus",
    "WiiiConnectProviderRegistryEntry",
    "WiiiConnectRequiredField",
    "WiiiConnectScopeGrant",
    "WiiiConnectSessionStartDecision",
    "WiiiConnectSessionStartRequest",
    "WiiiConnectVaultSecretRef",
    "WIII_CONNECT_PROVIDER_REGISTRY_VERSION",
    "WIII_CONNECT_SNAPSHOT_VERSION",
    "WiiiConnectionRecord",
    "WiiiConnectionScopes",
    "WiiiConnectionSnapshot",
    "WiiiPathCapabilityRecord",
    "begin_connection_session",
    "build_wiii_connect_snapshot",
    "decide_external_execution",
    "get_wiii_connect_provider_entry",
    "is_connection_baseline_ready",
    "list_wiii_connect_provider_registry",
    "normalize_connection_state",
    "provider_callback_decision",
    "provider_callback_decision_for_entry",
    "provider_connection_status",
    "provider_connection_status_for_entry",
    "provider_registry_public_metadata",
    "scope_grant_from_mapping",
]
